### ISSUE TITLE
`igc pipeline` command fails but doesnot give any error. Tasks donot get copied to target namespace

### ISSUE THREAD

**Issue by RamyaRaghuveera** [cloud-native-toolkit/ibm-garage-cloud-cli#379]
Env: ocp4.9, Azure 
Cluster details: https://console-openshift-console.apps.s1sfss3q.eastus.aroapp.io/
igc pipeline command doesnot give any error but fails to copy tasks to target namespace. Hence, PipelineRun fails with the following error: "Error retrieving pipeline for pipelinerun dev-rpp/azure-pipeline-test-180f2266ae2: error when listing pipelines for pipelineRun azure-pipeline-test-180f2266ae2: pipelines.tekton.dev "azure-pipeline-test" not found"

igc pipeline 
? Select the type of pipeline that should be run? Tekton
Creating pipeline on openshift cluster in dev-rpp namespace
Retrieving git parameters
Git credentials have already been stored for user: RamyaRaghuveera
  Project git repo: https://github.com/cloud-native-toolkit/ibm-garage-cloud-cli.git
  Branch: main
Retrieving available template pipelines from tools
Pipeline templates filtered based on detected runtime: nodejs
? Select the Pipeline to use in the PipelineRun: ibm-nodejs
? scan-image: Enable the pipeline to scan the image for vulnerabilities? No
? lint-dockerfile: Enable the pipeline to lint the Dockerfile for best practices? No
Copied Pipeline from tools/ibm-nodejs to dev-rpp/azure-pipeline-test
Creating TriggerTemplate for pipeline: azure-pipeline-test
Creating TriggerBinding for pipeline: azure-pipeline-test
Creating/updating TriggerEventListener for pipeline: tekton
  Waiting for event listener rollout: dev-rpp/el-tekton
Creating/updating Route for pipeline: tekton
Creating PipelineRun for pipeline: azure-pipeline-test
Creating Github webhook for repo: https://github.com/RamyaRaghuveera/azure-pipeline-test.git
Warning: Webhook already exists for this trigger in this repository.
Pipeline run started: azure-pipeline-test-180f2266ae2
Next steps:
  Tekton cli:
    View PipelineRun info - tkn pr describe azure-pipeline-test-180f2266ae2
    View PipelineRun logs - tkn pr logs -f azure-pipeline-test-180f2266ae2
  OpenShift console:
    View PipelineRun - https://console-openshift-console.apps.s1sfss3q.eastus.aroapp.io/k8s/ns/dev-rpp/tekton.dev~v1beta1~PipelineRun/azure-pipeline-test-180f2266ae2

**Comment by seansund** [comment]
This problem is caused when ArgoCD gitops is used to deploy the tekton resources (pipelines and tasks). The `app.kubernetes.io/instance` label is being copied with the task and ArgoCD thinks the resource is part of the application that provisioned the tekton tasks. Since it doesn't match any of the requested resources, the new task gets pruned.

The fix is to remove the label from the resource during copy. We can also provide an optional argument to the `pipeline` for the argocd instance label name in the scenario where the default label has been changed.
